### ISSUE TITLE
The x86 container image seems to be missing

### ISSUE THREAD

**Issue by brandonp42** [cncf/llm-starter-pack#1]
See https://hub.docker.com/r/onlydole/ollama-mistral/tags - it appears the only image available currently is ARM.

**Comment by onlydole** [comment]
Thank you, @brandonp42! We will take a look at this next week after KubeCon + CloudNativeCon NA wraps

**Comment by tommybobbins** [comment]
Similarly in kind/bot-deployment.yaml
https://hub.docker.com/r/pritianka/bot/tags
This is arm64 only.

**Comment by 1213adam** [comment]
Warning  Failed            25m (x6 over 27m)      kubelet            Error: ImagePullBackOff
  Normal   BackOff           2m28s (x107 over 27m)  kubelet            Back-off pulling image "onlydole/ollama-mistral:latest"

**Comment by jtonello** [comment]
I managed to get the LLM to deploy on amd64 using the stock ollama/ollama image, but the final bit -- the bot-deployment.yaml -- references an arm-only image. Perhaps posting the Dockerfile for the bot would be sufficient to allow full deployment on non-arm systems.

**Comment by fivehorizons** [comment]
Same issue.  Will try an ARM EC2

**Comment by mmoore0011** [comment]
If the source and Dockerfile for the 2 images is available somewhere, I'd be happy to test build on intel/amd and make a PR.  I'm dying to try this...

**Comment by castrojo** [comment]
Hi everyone, sorry for the delay!

We've gone ahead an automated building the container here. That means a fresh one with each PR! It's getting late so I haven't had a chance to try so give it a whirl! 

    docker pull ghcr.io/cncf/llm-starter-pack:latest

If any of you have the expertise to make [the github action](https://github.com/cncf/llm-starter-pack/blob/main/.github/workflows/build.yml) better it would be appreciated! 

It'd be great to have a full set of artifacthub labels, convenience tags, and some more placeholder documentation. So that we can just have one kit to make anyone's demos autobuilding. Feedback appreciated!

https://github.com/cncf/llm-starter-pack/pkgs/container/llm-starter-pack

**Comment by onlydole** [comment]
We have added these new dynamic builds (thank you again @castrojo for working on these), and any PRs/Issues/improvements are welcome.
